#!/usr/bin/env node
/**
 * WorkOS provisioning helper — run this where WorkOS is reachable.
 *
 * Inspects the FORGE workspace and prints exactly what the apps need:
 * organizations, their SSO connections, and the SQL to map email domains onto
 * them. Read-only by default; pass --write-sql to emit a file you can apply.
 *
 * Usage:
 *   WORKOS_API_KEY=sk_... node scripts/workos-setup.mjs
 *   WORKOS_API_KEY=sk_... node scripts/workos-setup.mjs --write-sql
 *
 * Why a script and not the app: the SSO handshake needs a WorkOS organization
 * id per email domain, and nothing in the codebase can invent those — they
 * come from your workspace. This reads them out and hands you the rows.
 */

import { writeFileSync } from 'node:fs';
import { WorkOS } from '@workos-inc/node';

const apiKey = process.env.WORKOS_API_KEY;
const clientId = process.env.WORKOS_CLIENT_ID;

if (!apiKey) {
  console.error('WORKOS_API_KEY is not set.\n');
  console.error('Find it at https://dashboard.workos.com → API Keys, then:');
  console.error('  WORKOS_API_KEY=sk_... node scripts/workos-setup.mjs');
  process.exit(1);
}

const workos = new WorkOS(apiKey, clientId ? { clientId } : undefined);
const writeSql = process.argv.includes('--write-sql');

const REDIRECT_URIS = [
  'http://localhost:3000/api/auth/sso/callback', // apps/platform
  'http://localhost:3001/api/auth/sso/callback', // apps/dashboard
];

async function main() {
  console.log('Connecting to WorkOS…\n');

  const { data: organizations } = await workos.organizations.listOrganizations({ limit: 100 });

  if (organizations.length === 0) {
    console.log('No organizations exist in this workspace yet.\n');
    console.log('Create one at https://dashboard.workos.com → Organizations,');
    console.log('add an SSO connection to it, then re-run this script.');
    return;
  }

  console.log(`Found ${organizations.length} organization(s):\n`);

  const rows = [];

  for (const org of organizations) {
    const domains = (org.domains ?? []).map((d) => d.domain ?? d).filter(Boolean);
    console.log(`  ${org.name}`);
    console.log(`    id       ${org.id}`);
    console.log(`    domains  ${domains.length ? domains.join(', ') : '(none configured)'}`);

    // Connections are what actually make SSO work; an organization without one
    // will fail the handshake at redirect time rather than at configuration time.
    let connections = [];
    try {
      const res = await workos.sso.listConnections({ organizationId: org.id, limit: 20 });
      connections = res.data ?? [];
    } catch (err) {
      console.log(`    sso      ! could not list connections: ${err.message}`);
    }

    if (connections.length === 0) {
      console.log('    sso      NONE — this org cannot complete an SSO login yet');
    } else {
      for (const c of connections) {
        console.log(`    sso      ${c.connectionType}  ${c.state}  (${c.id})`);
      }
    }

    for (const domain of domains) {
      rows.push({ domain, orgId: org.id, orgName: org.name });
    }
    console.log('');
  }

  if (rows.length === 0) {
    console.log('No organization has a verified domain, so no domain→org rows can be');
    console.log('generated. Add domains under each organization in the WorkOS dashboard.\n');
  } else {
    const sql = [
      '-- Generated by scripts/workos-setup.mjs',
      '-- Maps email domains onto WorkOS organizations so "Sign in with SSO" can route.',
      '',
      ...rows.map(
        (r) =>
          `INSERT INTO sso_domains (domain, workos_organization_id) VALUES ('${r.domain}', '${r.orgId}')\n` +
          `  ON CONFLICT (domain) DO UPDATE SET workos_organization_id = EXCLUDED.workos_organization_id;  -- ${r.orgName}`,
      ),
      '',
    ].join('\n');

    if (writeSql) {
      const out = new URL('./sso-domains.generated.sql', import.meta.url).pathname;
      writeFileSync(out, sql);
      console.log(`Wrote ${rows.length} row(s) to ${out}`);
      console.log('Apply with:  psql "$DATABASE_URL" -f scripts/sso-domains.generated.sql\n');
    } else {
      console.log('Apply these to the dashboard database (or re-run with --write-sql):\n');
      console.log(sql);
    }
  }

  console.log('Redirect URIs — each must be registered verbatim in the WorkOS');
  console.log('dashboard under Redirects, or the callback is rejected:');
  for (const uri of REDIRECT_URIS) console.log(`  ${uri}`);
  console.log('');
  console.log('MFA needs no provisioning: factors are created per merchant at');
  console.log('enrollment time via POST /api/mfa/enroll.');
}

main().catch((err) => {
  console.error('\nFailed:', err.message);
  if (err.status === 401) {
    console.error('That API key was rejected — check you copied the whole value.');
  }
  process.exit(1);
});
