/**
 * Groth16Verifier contract tests (Hardhat + ethers v6)
 *
 * These tests verify the contract interface works correctly in stub mode.
 * When the real Groth16 verifier is deployed, update the test with:
 *   1. Valid proof bytes (generated by arkworks/snarkjs)
 *   2. Valid public inputs matching the circuit's expected layout
 *   3. Invalid proof test that expects revert
 *
 * CURRENT STATE: STUB MODE — all proofs accepted unconditionally.
 * TODO: After circuit finalization, add real proof/input test vectors.
 */

import { expect } from 'chai';
import { ethers } from 'hardhat';

describe('Groth16Verifier', () => {
  let verifier: any;

  beforeEach(async () => {
    const Factory = await ethers.getContractFactory('Groth16Verifier');
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();
  });

  describe('verifyProof', () => {
    it('returns true for any proof in stub mode', async () => {
      const proofBytes   = ethers.toUtf8Bytes('stub_proof_bytes');
      const publicInputs = [
        ethers.zeroPadValue(ethers.toBeHex(42), 32),   // merkle root
        ethers.zeroPadValue(ethers.toBeHex(100), 32),  // nullifier
        ethers.zeroPadValue(ethers.toBeHex(1000), 32), // amount
      ];

      // STUB: always returns true
      const valid = await verifier.verifyProof(proofBytes, publicInputs);
      expect(valid).to.equal(true);
    });

    it('emits ProofVerified event when proof is accepted', async () => {
      const nullifierHex = ethers.zeroPadValue(ethers.toBeHex(12345), 32);
      const rootHex      = ethers.zeroPadValue(ethers.toBeHex(67890), 32);

      await expect(
        verifier.verifyProof(
          ethers.toUtf8Bytes('proof'),
          [
            BigInt(rootHex),
            BigInt(nullifierHex),
            1_000_000n,
          ]
        )
      )
        .to.emit(verifier, 'ProofVerified')
        .withArgs(nullifierHex, rootHex, await (await ethers.getSigners())[0].getAddress());
    });

    it('reverts when no public inputs provided', async () => {
      await expect(
        verifier.verifyProof(ethers.toUtf8Bytes('proof'), [])
      ).to.be.revertedWith('Groth16Verifier: no public inputs');
    });
  });

  describe('verifyDepositProof', () => {
    it('returns true for any deposit proof in stub mode', async () => {
      const valid = await verifier.verifyDepositProof(
        ethers.toUtf8Bytes('deposit_proof'),
        ethers.zeroPadValue(ethers.toBeHex(999), 32),
        0n // USDC asset ID
      );
      expect(valid).to.equal(true);
    });
  });

  describe('verifyWithdrawProof', () => {
    it('returns true for any withdraw proof in stub mode', async () => {
      const valid = await verifier.verifyWithdrawProof(
        ethers.toUtf8Bytes('withdraw_proof'),
        ethers.zeroPadValue(ethers.toBeHex(777), 32),
        ethers.zeroPadValue(ethers.toBeHex(888), 32),
        1_000_000n
      );
      expect(valid).to.equal(true);
    });
  });

  describe('version', () => {
    it('returns stub version string', async () => {
      expect(await verifier.version()).to.equal('0.1.0-stub');
    });
  });
});
