{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "liquidity-forecaster.fullname" . }}
  labels:
    {{- include "liquidity-forecaster.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liquidity-forecaster.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: /metrics
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          targetLabel: app
{{- end }}
