apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-enterprise-treasury
  labels:
    app: enterprise-treasury
    app.kubernetes.io/name: enterprise-treasury
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: enterprise-treasury
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: enterprise-treasury
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: enterprise-treasury
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: BANK_CONNECTIVITY_URL
              value: {{ .Values.bankConnectivityUrl | quote }}
            - name: YIELD_ENGINE_URL
              value: {{ .Values.yieldEngineUrl | quote }}
            - name: RATE_LIMIT_PER_MIN
              value: {{ .Values.rateLimitPerMinute | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
