apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-negotiation
  labels:
    app: agent-negotiation
    app.kubernetes.io/name: agent-negotiation
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: agent-negotiation
    app.kubernetes.io/instance: {{ .Release.Name }}
