apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing-engine.fullname" . }}
  labels:
    {{- include "billing-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "billing-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "billing-engine.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: billing-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CATALINA_OPTS
              value: {{ .Values.env.CATALINA_OPTS | quote }}
            - name: KILLBILL_MODES
              value: {{ .Values.env.KILLBILL_MODES | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.mysql.port | quote }}
            - name: MYSQL_DB
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              value: "killbill"
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
