apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-forge-custody
  labels:
    app: forge-custody
spec:
  type: {{ .Values.service.type }}
  selector:
    app: forge-custody
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
