apiVersion: v1
kind: Service
metadata:
  name: agent-credit-bureau
  labels:
    app: agent-credit-bureau
spec:
  type: {{ .Values.service.type }}
  selector:
    app: agent-credit-bureau
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
