// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.23;

/**
 * @title Groth16Verifier
 * @notice On-chain verifier for Groth16 proofs (BN254 curve).
 *
 * ARCH: This contract verifies zero-knowledge proofs generated by the
 * auditable-privacy-payment Rust circuit. The proof asserts that:
 *   - A shielded transaction was validly formed (commitment is correctly computed)
 *   - The prover knows the secret key and blinding factor
 *   - Balance is preserved across UTXOs (sum(inputs) == sum(outputs))
 *   - No double-spending (nullifier is unique)
 *
 * IMPLEMENTATION: Uses BN254 EVM precompiles:
 *   - ecAdd     (0x06): G1 point addition
 *   - ecMul     (0x07): G1 scalar multiplication
 *   - ecPairing (0x08): BN254 bilinear pairing check
 *
 * Verification equation (Groth16):
 *   e(π_A, π_B) == e(α, β) * e(vk_x, γ) * e(π_C, δ)
 *
 * Implemented as a single 4-pairing check equal to 1:
 *   e(-π_A, π_B) * e(α, β) * e(vk_x, γ) * e(π_C, δ) == 1
 *
 * Where: vk_x = IC[0] + Σ(publicInputs[i] * IC[i+1])
 *
 * ACTIVATION:
 *   1. Deploy contract (starts in stubMode=true, no real VK)
 *   2. After circuit finalization: call setVerifyingKey() for each circuit
 *   3. Call setStubMode(false) to enforce real pairing checks
 *
 * @dev Based on tornado-cash / snarkjs verifier pattern.
 *   See: https://github.com/iden3/snarkjs/blob/master/templates/verifier_groth16.sol
 */

// ─── Pairing Library ──────────────────────────────────────────────────────────

library Pairing {

    // BN254 field modulus
    uint256 constant FIELD_MODULUS =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    // G2 point: coordinates are Fq2 elements represented as [c0, c1]
    // where the element is c0 + c1*i (i = sqrt(-1) in Fq2)
    struct G2Point {
        uint256[2] X; // [X.c0, X.c1]
        uint256[2] Y; // [Y.c0, Y.c1]
    }

    /// @notice Negate a G1 point (returns the additive inverse).
    /// @dev Negation on BN254: negate Y coordinate mod field modulus.
    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) {
            return G1Point(0, 0); // point at infinity
        }
        return G1Point(p.X, FIELD_MODULUS - (p.Y % FIELD_MODULUS));
    }

    /// @notice Add two G1 points using the ecAdd precompile (0x06).
    function addition(G1Point memory p1, G1Point memory p2)
        internal
        view
        returns (G1Point memory r)
    {
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;

        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(gas(), 0x06, input, 0x80, r, 0x40)
        }
        require(success, "Pairing: ecAdd failed");
    }

    /// @notice Scalar-multiply a G1 point by a scalar using ecMul precompile (0x07).
    function scalar_mul(G1Point memory p, uint256 s)
        internal
        view
        returns (G1Point memory r)
    {
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;

        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(gas(), 0x07, input, 0x60, r, 0x40)
        }
        require(success, "Pairing: ecMul failed");
    }

    /// @notice Run a multi-pairing check using the ecPairing precompile (0x08).
    /// @param p1 Array of G1 points
    /// @param p2 Array of G2 points (same length as p1)
    /// @return result True if the product of pairings equals 1 (identity)
    function pairing(G1Point[] memory p1, G2Point[] memory p2)
        internal
        view
        returns (bool result)
    {
        require(p1.length == p2.length, "Pairing: length mismatch");

        uint256 len = p1.length;
        // Each pair encodes as 6 uint256 values (G1: 2, G2: 4)
        uint256 inputLen = len * 6;
        uint256[] memory input = new uint256[](inputLen);

        for (uint256 i = 0; i < len; i++) {
            uint256 base = i * 6;
            input[base + 0] = p1[i].X;
            input[base + 1] = p1[i].Y;
            // G2 encoding for ecPairing: X = [X.c1, X.c0], Y = [Y.c1, Y.c0]
            // (imaginary part first, then real part)
            input[base + 2] = p2[i].X[1];
            input[base + 3] = p2[i].X[0];
            input[base + 4] = p2[i].Y[1];
            input[base + 5] = p2[i].Y[0];
        }

        uint256 inputByteLen = inputLen * 32;
        uint256[1] memory out;
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(
                gas(),
                0x08,
                add(input, 0x20), // skip array length prefix
                inputByteLen,
                out,
                0x20
            )
        }
        require(success, "Pairing: ecPairing precompile failed");
        result = out[0] == 1;
    }

    /// @notice Convenience: check 4-pairing product equals identity.
    function pairingProd4(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {
        G1Point[] memory p1 = new G1Point[](4);
        G2Point[] memory p2 = new G2Point[](4);
        p1[0] = a1; p2[0] = a2;
        p1[1] = b1; p2[1] = b2;
        p1[2] = c1; p2[2] = c2;
        p1[3] = d1; p2[3] = d2;
        return pairing(p1, p2);
    }
}

// ─── Main Contract ────────────────────────────────────────────────────────────

contract Groth16Verifier {
    using Pairing for *;

    // ── Public Inputs Layout ──────────────────────────────────────────────────
    //
    // Groth16 proof public inputs for the Transfer circuit:
    //   publicInputs[0] = Merkle root (commitment tree root)
    //   publicInputs[1] = Nullifier (unique per UTXO + spender)
    //   publicInputs[2] = Freezer hash (auditor enforcement)
    //   publicInputs[3] = Auditor public key (x-coordinate)
    //   publicInputs[4] = Auditor public key (y-coordinate)
    //   publicInputs[5] = Encrypted amount (ElGamal ciphertext)
    //
    // TODO: Actual layout depends on final circuit design in auditable-privacy-payment.

    // ── Circuit IDs ───────────────────────────────────────────────────────────

    uint8 public constant CIRCUIT_TRANSFER = 0;
    uint8 public constant CIRCUIT_DEPOSIT  = 1;
    uint8 public constant CIRCUIT_WITHDRAW = 2;

    // ── Stub Mode ─────────────────────────────────────────────────────────────

    /// @notice When true, pairing check is skipped and all proofs are accepted.
    /// Flip to false via setStubMode(false) after circuit finalization + VK injection.
    bool public stubMode;

    // ── Access Control ────────────────────────────────────────────────────────

    address public owner;

    modifier onlyOwner() {
        require(msg.sender == owner, "Groth16Verifier: caller is not owner");
        _;
    }

    // ── Structs ───────────────────────────────────────────────────────────────

    struct VerifyingKey {
        Pairing.G1Point alfa1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC; // IC[0] + Σ(IC[i+1] * publicInputs[i]) = vk_x
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    // Packed storage for a single G1 point
    struct StoredG1 { uint256 x; uint256 y; }

    // Packed storage for a single G2 point (Fq2 coords)
    struct StoredG2 { uint256[2] x; uint256[2] y; }

    // On-chain storage for a circuit's verifying key.
    // IC stored as parallel arrays (dynamic-length arrays inside a struct are
    // stored as separate mappings under the hood; this layout is gas-efficient).
    struct StoredVK {
        bool      isSet;
        StoredG1  alfa1;
        StoredG2  beta2;
        StoredG2  gamma2;
        StoredG2  delta2;
        uint256[] icX;
        uint256[] icY;
    }

    // ── VK Storage ────────────────────────────────────────────────────────────

    StoredVK private _transferVK;
    StoredVK private _depositVK;
    StoredVK private _withdrawVK;

    // ── Events ────────────────────────────────────────────────────────────────

    /// @dev Emitted when a proof is successfully verified.
    event ProofVerified(
        bytes32 indexed nullifier,
        bytes32 indexed merkleRoot,
        address indexed verifier
    );

    /// @dev Emitted when a circuit's verifying key is updated.
    /// @param circuitId  0=transfer, 1=deposit, 2=withdraw
    /// @param setBy      Address that called setVerifyingKey
    event VerifyingKeyUpdated(uint8 indexed circuitId, address indexed setBy);

    /// @dev Emitted when stub mode is toggled.
    event StubModeChanged(bool enabled);

    // ── Constructor ───────────────────────────────────────────────────────────

    constructor() {
        owner    = msg.sender;
        // Start in stub mode. Call setStubMode(false) after injecting all VKs.
        stubMode = true;
    }

    // ── Admin Functions ───────────────────────────────────────────────────────

    /// @notice Transfer ownership to a new address (e.g. timelock or multisig).
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Groth16Verifier: zero address");
        owner = newOwner;
    }

    /// @notice Enable or disable stub mode.
    /// Production: call setStubMode(false) only after all three VKs are set.
    function setStubMode(bool enabled) external onlyOwner {
        stubMode = enabled;
        emit StubModeChanged(enabled);
    }

    /**
     * @notice Inject a circuit's verifying key into contract storage.
     *
     * Call this once per circuit after `snarkjs zkey export solidityverifier`
     * produces the VK parameters. Then call setStubMode(false).
     *
     * @param circuitId   0=transfer, 1=deposit, 2=withdraw (see CIRCUIT_* constants)
     * @param alfa1       G1 point α: [x, y]
     * @param beta2       G2 point β: [[X.c0, X.c1], [Y.c0, Y.c1]]
     * @param gamma2      G2 point γ: same encoding
     * @param delta2      G2 point δ: same encoding
     * @param icX         IC x-coordinates, length = nPublicInputs + 1
     * @param icY         IC y-coordinates, same length as icX
     */
    function setVerifyingKey(
        uint8             circuitId,
        uint256[2]    calldata alfa1,
        uint256[2][2] calldata beta2,
        uint256[2][2] calldata gamma2,
        uint256[2][2] calldata delta2,
        uint256[]     calldata icX,
        uint256[]     calldata icY
    ) external onlyOwner {
        require(icX.length == icY.length && icX.length >= 2,
            "Groth16Verifier: IC length must be >= 2 (nInputs+1)");

        StoredVK storage vk = _storedVK(circuitId);

        vk.isSet  = true;
        vk.alfa1  = StoredG1(alfa1[0], alfa1[1]);
        vk.beta2  = StoredG2([beta2[0][0],  beta2[0][1]],
                              [beta2[1][0],  beta2[1][1]]);
        vk.gamma2 = StoredG2([gamma2[0][0], gamma2[0][1]],
                              [gamma2[1][0], gamma2[1][1]]);
        vk.delta2 = StoredG2([delta2[0][0], delta2[0][1]],
                              [delta2[1][0], delta2[1][1]]);
        vk.icX    = icX;
        vk.icY    = icY;

        emit VerifyingKeyUpdated(circuitId, msg.sender);
    }

    /// @notice Returns true if the given circuit's VK has been set.
    function isVKSet(uint8 circuitId) external view returns (bool) {
        return _storedVK(circuitId).isSet;
    }

    // ── Verification Keys ─────────────────────────────────────────────────────

    /**
     * @notice Returns the transfer circuit verification key.
     * Returns the on-chain stored VK if set; otherwise a placeholder zero VK
     * that is only valid while stubMode=true.
     */
    function verifyingKey() internal view returns (VerifyingKey memory vk) {
        if (_transferVK.isSet) return _loadStoredVK(_transferVK);
        vk.alfa1  = Pairing.G1Point(0, 0);
        vk.beta2  = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.gamma2 = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.delta2 = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.IC     = new Pairing.G1Point[](7); // 6 public inputs + constant term
    }

    /**
     * @notice Returns the deposit circuit verification key.
     */
    function depositVerifyingKey() internal view returns (VerifyingKey memory vk) {
        if (_depositVK.isSet) return _loadStoredVK(_depositVK);
        vk.alfa1  = Pairing.G1Point(0, 0);
        vk.beta2  = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.gamma2 = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.delta2 = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.IC     = new Pairing.G1Point[](3); // commitment + assetId + constant
    }

    /**
     * @notice Returns the withdraw circuit verification key.
     */
    function withdrawVerifyingKey() internal view returns (VerifyingKey memory vk) {
        if (_withdrawVK.isSet) return _loadStoredVK(_withdrawVK);
        vk.alfa1  = Pairing.G1Point(0, 0);
        vk.beta2  = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.gamma2 = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.delta2 = Pairing.G2Point([uint256(0), 0], [uint256(0), 0]);
        vk.IC     = new Pairing.G1Point[](4); // nullifier + root + amount + constant
    }

    // ── Internal Helpers ──────────────────────────────────────────────────────

    function _storedVK(uint8 circuitId) internal view returns (StoredVK storage) {
        if (circuitId == CIRCUIT_TRANSFER) return _transferVK;
        if (circuitId == CIRCUIT_DEPOSIT)  return _depositVK;
        if (circuitId == CIRCUIT_WITHDRAW) return _withdrawVK;
        revert("Groth16Verifier: unknown circuitId");
    }

    function _loadStoredVK(StoredVK storage s) internal view returns (VerifyingKey memory vk) {
        vk.alfa1  = Pairing.G1Point(s.alfa1.x, s.alfa1.y);
        vk.beta2  = Pairing.G2Point(s.beta2.x,  s.beta2.y);
        vk.gamma2 = Pairing.G2Point(s.gamma2.x, s.gamma2.y);
        vk.delta2 = Pairing.G2Point(s.delta2.x, s.delta2.y);
        uint256 n = s.icX.length;
        vk.IC     = new Pairing.G1Point[](n);
        for (uint256 i = 0; i < n; i++) {
            vk.IC[i] = Pairing.G1Point(s.icX[i], s.icY[i]);
        }
    }

    // ── Core Verification Logic ───────────────────────────────────────────────

    /**
     * @notice Core Groth16 verification.
     *
     * Checks: e(-π_A, π_B) * e(α, β) * e(vk_x, γ) * e(π_C, δ) == 1
     *
     * @param input  Public input array (field elements, BN254 scalar field)
     * @param proof  Decoded proof (π_A, π_B, π_C)
     * @param vk     Verification key
     * @return 0 on success, 1 on failure
     */
    function verify(
        uint256[] memory input,
        Proof memory proof,
        VerifyingKey memory vk
    ) internal view returns (uint256) {
        require(input.length + 1 == vk.IC.length, "Groth16Verifier: input/IC length mismatch");

        // In stub mode, skip the pairing check entirely
        if (stubMode) {
            return 0;
        }

        // Compute vk_x = IC[0] + Σ(IC[i+1] * input[i])
        Pairing.G1Point memory vk_x = Pairing.G1Point(vk.IC[0].X, vk.IC[0].Y);
        for (uint256 i = 0; i < input.length; i++) {
            require(
                input[i] < Pairing.FIELD_MODULUS,
                "Groth16Verifier: input out of field"
            );
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }

        // Check 4-pairing product equals identity
        bool valid = Pairing.pairingProd4(
            Pairing.negate(proof.A), proof.B,   // e(-π_A, π_B)
            vk.alfa1,                vk.beta2,   // e(α, β)
            vk_x,                    vk.gamma2,  // e(vk_x, γ)
            proof.C,                 vk.delta2   // e(π_C, δ)
        );

        return valid ? 0 : 1;
    }

    /**
     * @notice Decode a proof from ABI-encoded bytes.
     * @dev Expected encoding: abi.encode(uint256[2] pi_a, uint256[2][2] pi_b, uint256[2] pi_c)
     */
    function _decodeProof(bytes calldata proofBytes) internal pure returns (Proof memory proof) {
        (
            uint256[2] memory pi_a,
            uint256[2][2] memory pi_b,
            uint256[2] memory pi_c
        ) = abi.decode(proofBytes, (uint256[2], uint256[2][2], uint256[2]));

        proof.A = Pairing.G1Point(pi_a[0], pi_a[1]);
        // G2 points: pi_b[0] = X coords, pi_b[1] = Y coords
        proof.B = Pairing.G2Point(
            [pi_b[0][0], pi_b[0][1]],
            [pi_b[1][0], pi_b[1][1]]
        );
        proof.C = Pairing.G1Point(pi_c[0], pi_c[1]);
    }

    // ── Proof Verification ────────────────────────────────────────────────────

    /**
     * @notice Verify a Groth16 proof for a shielded transfer.
     *
     * @param proofBytes   ABI-encoded proof: abi.encode(uint256[2], uint256[2][2], uint256[2])
     * @param publicInputs Circuit public inputs (see Public Inputs Layout above)
     * @return valid True if proof is valid
     */
    function verifyProof(
        bytes calldata proofBytes,
        uint256[] calldata publicInputs
    ) external returns (bool valid) {
        require(publicInputs.length > 0, "Groth16Verifier: no public inputs");

        Proof memory proof = _decodeProof(proofBytes);
        uint256[] memory inputs = new uint256[](publicInputs.length);
        for (uint256 i = 0; i < publicInputs.length; i++) {
            inputs[i] = publicInputs[i];
        }

        VerifyingKey memory vk = verifyingKey();
        uint256 result = verify(inputs, proof, vk);
        valid = (result == 0);

        if (valid && publicInputs.length >= 2) {
            bytes32 nullifier  = bytes32(publicInputs[1]);
            bytes32 merkleRoot = bytes32(publicInputs[0]);
            emit ProofVerified(nullifier, merkleRoot, msg.sender);
        }
    }

    /**
     * @notice Verify a Groth16 proof for a deposit operation.
     *
     * Deposit circuit proves: commitment = Poseidon(asset, amount, blind, owner_pk)
     * without revealing asset, amount, or blind.
     *
     * @param proofBytes ABI-encoded Groth16 proof
     * @param commitment The commitment being deposited
     * @param assetId    The asset type (0=USDC, 1=USDT)
     * @return valid True if proof is valid
     */
    function verifyDepositProof(
        bytes calldata proofBytes,
        bytes32 commitment,
        uint256 assetId
    ) external view returns (bool valid) {
        if (stubMode) return true;
        uint256[] memory inputs = new uint256[](2);
        inputs[0] = uint256(commitment);
        inputs[1] = assetId;
        Proof memory proof = _decodeProof(proofBytes);
        return verify(inputs, proof, depositVerifyingKey()) == 0;
    }

    /**
     * @notice Verify a Groth16 proof for a withdrawal operation.
     *
     * Withdraw circuit proves: the withdrawer knows the secret key for a UTXO
     * without revealing the UTXO's commitment.
     *
     * @param proofBytes  ABI-encoded Groth16 proof
     * @param nullifier   The nullifier being consumed (prevents double-spending)
     * @param merkleRoot  The Merkle tree root the UTXO is a member of
     * @param amountUnits The amount being withdrawn (revealed for settlement)
     * @return valid True if proof is valid
     */
    function verifyWithdrawProof(
        bytes calldata proofBytes,
        bytes32 nullifier,
        bytes32 merkleRoot,
        uint256 amountUnits
    ) external view returns (bool valid) {
        if (stubMode) return true;
        uint256[] memory inputs = new uint256[](3);
        inputs[0] = uint256(nullifier);
        inputs[1] = uint256(merkleRoot);
        inputs[2] = amountUnits;
        Proof memory proof = _decodeProof(proofBytes);
        return verify(inputs, proof, withdrawVerifyingKey()) == 0;
    }

    /**
     * @notice Returns the current contract version.
     * @dev Used by NullifierRegistry and CommitmentTree to detect version mismatches.
     */
    function version() external pure returns (string memory) {
        return "0.3.0";
    }
}
